version: "3.1"
services:
  frontend:
    image: ammartahircs/student-management-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
      - "db"
    expose:
      - "3000"
  backend:
    image: ammartahircs/student-management-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - "db"
    environment:
      WAIT_HOSTS: db:3306
      DATABASE_HOST: "db"
  db:
    image: ammartahircs/student-management-db:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
