apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: ammartahircs/student-management-frontend:latest
          name: frontend
          env:
          - name: URL
            value: "107.21.196.221"
          - name: BACKEND_PORT
            value: "5000"
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
